title: Blog for Subhrodip Mohanta
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_style: grid
palette: green
header:
  title: Subhrodip Mohanta
  logo_img_alt: Ampersand Logo
  has_nav: true
  nav_links:
    - label: Blog Home
      url: /
      style: link
    - label: Main Website
      url: 'https://subho.xyz'
      new_window: true
      style: link
    - label: GitHub
      url: 'https://github.com/ohbus'
      style: link
      new_window: true
    - label: Contact
      url: 'https://subho.xyz/site/en/contact.html'
      style: link
      new_window: true
footer:
  content: >-
    &copy; Stackbit. All rights reserved.
  has_social: true
  social_links:
    - label: GitHub
      url: 'https://github.com/ohbus'
      style: icon
      icon_class: github
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/in/ohbusm'
      style: icon
      icon_class: linkedin
      new_window: true
    - label: DEV
      url: 'https://dev.to/ohbus'
      style: icon
      icon_class: dev
      new_window: true
    - label: Twitter
      url: 'https://twitter.com/sohbus'
      style: icon
      icon_class: twitter
      new_window: true
  has_subscribe: true
  subscribe_title: Subscribe for new updates
  subscribe_content: >-
    Subscribe to my email newsletter to receive useful articles and special
    offers. This monthly email is sent out on the first of every month.
  subscribe_action: /subscribe-success
  links:
    - label: Original Website
      url: 'https://subho.xyz'
      new_window: true
      style: link
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
